[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[project]
name = "soyokaze"
version = "0.6.1"
description = "Python bindings for soyokaze, an HTTP/1, HTTP/2 and HTTP/3 library"
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"

[project.urls]
Repository = "https://github.com/nercone-dev/soyokaze/"

[tool.setuptools.packages.find]
include = ["soyokaze*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[dependency-groups]
dev = ["pytest", "pytest-asyncio"]
